name: "Check if image persists in registry"
description: "Check if image persists in registry"

inputs:
  image:
    required: true
    type: string
  tag:
    required: false
    type: string
  arch:
    required: false
    type: string
    default: "linux/amd64"

outputs:
  exists:
    value: ${{ steps.check_image.outputs.exists }}

runs:
  using: "composite"
  steps:
    - id: check_image
      env:
        IMAGE: ${{ inputs.image }}
        TAG: ${{ inputs.tag }}
        ARCH: ${{ inputs.arch }}
      run: |
        if docker manifest inspect "$IMAGE:$TAG" | jq '.manifests[].platform | [.os, .architecture] | join("/")' | grep -qi "$ARCH"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
        else
            echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
