name: "Login to registry"
description: "Login to registry depending on registry type"

inputs:
  registry:
    type: string
    required: true
  gcp_service_account_key:
    required: false
    type: string
  dockerhub_login:
    required: false
    type: string
  dockerhub_password:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set registry type
      id: registry
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
      run: |
        if [[ "$REGISTRY" =~ ^.*-docker.pkg.dev.*$ ]]; then
            echo "type=gcp" >> "$GITHUB_OUTPUT"
        else
            echo "type=dockerhub" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to GCR
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        registry: ${{ inputs.registry }}
        username: _json_key_base64
        password: ${{ inputs.gcp_service_account_key }}
      if: steps.registry.outputs.type == 'gcp'

    - name: Login to Docker Hub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        username: ${{ inputs.dockerhub_login }}
        password: ${{ inputs.dockerhub_password }}
      if: steps.registry.outputs.type == 'dockerhub'
